export const types = {
  // Milestone actions
  EDIT: 'EDIT',
  POST: 'POST',
  DELETE: 'DELETE',
  ADD_PREVIEW_IMG: 'ADD_PREVIEW_IMG',
  ADD_IMG: 'ADD_IMG',
  DEL_IMG: 'DEL_IMG',
  CHOOSE_LAYOUT: 'CHOOSE_LAYOUT',
  CHANGE_MILESTONE_TITLE: 'CHANGE_MILESTONE_TITLE',
  CHANGE_MILESTONE_TIME: 'CHANGE_MILESTONE_TIME',
  CHANGE_MILESTONE_CONTENT: 'CHANGE_MILESTONE_CONTENT',
  CHANGE_MILESTONE_TIP: 'CHANGE_MILESTONE_TIP',
  CHANGE_MILESTONE_PLACE_INFO: 'CHANGE_MILESTONE_PLACE_INFO',

  // Trip actions
  CHANGE_TRIP_TITLE: 'CHANGE_TRIP_TITLE',
  CHANGE_TRIP_COST: 'CHANGE_TRIP_COST',
  CHANGE_TRIP_CITY: 'CHANGE_TRIP_CITY',
  CHANGE_TRIP_STARTDATE: 'CHANGE_TRIP_STARTDATE',
  SUBMIT: 'SUBMIT'
};